### ISSUE TITLE
Order the "Missing Data" google spreadsheet by the scan date (`Entry_date`)

### ISSUE THREAD

**Issue by kcho** [AMP-SCZ/qqc#17]
The table in the `Missing Data` tab on MRI team's google spreadsheet shows missing MRI data. The table needs to be ordereed by `scan date`. Because when we contact each network for missing data, we highlight the MRI data with an earlier scan date. An earlier scan date in this missing data table would mean the site takes longer to update the data.

**Comment by nickckim** [comment]
This has been addressed with the new update.
